export const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  MILESTONE_NOT_FOUND: "MILESTONE_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  CAPABILITY_NOT_FOUND: "CAPABILITY_NOT_FOUND",
  SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",
  INVALID_RESOURCE_SCOPE: "INVALID_RESOURCE_SCOPE",
  INVALID_RESOURCE_LOCATION: "INVALID_RESOURCE_LOCATION",
  INVALID_CAPABILITY_RESOURCE_KIND: "INVALID_CAPABILITY_RESOURCE_KIND",
  RESOURCE_IN_USE: "RESOURCE_IN_USE",
  CONTENT_ALREADY_EXISTS: "CONTENT_ALREADY_EXISTS",
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",
  CONTENT_CONFLICT: "CONTENT_CONFLICT",
  CONTENT_TOO_LARGE: "CONTENT_TOO_LARGE",
  RESOURCE_CONTENT_UNSUPPORTED: "RESOURCE_CONTENT_UNSUPPORTED",
  CONTENT_PROVIDER_ERROR: "CONTENT_PROVIDER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
