import { z } from "@hono/zod-openapi";

import { ERROR_CODES, type ErrorCode } from "./error-codes";
export { ERROR_CODES, type ErrorCode } from "./error-codes";

/**
 * 固定顺序的错误码清单，同时用于 OpenAPI enum。
 * 新增错误码必须在此登记，保证运行时错误与文档声明一致。
 */
const ERROR_CODE_VALUES = [
  ERROR_CODES.BAD_REQUEST,
  ERROR_CODES.UNAUTHORIZED,
  ERROR_CODES.NOT_FOUND,
  ERROR_CODES.INTERNAL_ERROR,
  ERROR_CODES.PROJECT_NOT_FOUND,
  ERROR_CODES.MILESTONE_NOT_FOUND,
  ERROR_CODES.TASK_NOT_FOUND,
  ERROR_CODES.RESOURCE_NOT_FOUND,
  ERROR_CODES.CAPABILITY_NOT_FOUND,
  ERROR_CODES.SLUG_ALREADY_EXISTS,
  ERROR_CODES.INVALID_RESOURCE_SCOPE,
  ERROR_CODES.INVALID_RESOURCE_LOCATION,
  ERROR_CODES.INVALID_CAPABILITY_RESOURCE_KIND,
  ERROR_CODES.RESOURCE_IN_USE,
  ERROR_CODES.CONTENT_ALREADY_EXISTS,
  ERROR_CODES.CONTENT_NOT_FOUND,
  ERROR_CODES.CONTENT_CONFLICT,
  ERROR_CODES.CONTENT_TOO_LARGE,
  ERROR_CODES.RESOURCE_CONTENT_UNSUPPORTED,
  ERROR_CODES.CONTENT_PROVIDER_ERROR,
  ERROR_CODES.FINANCE_SETTINGS_REQUIRED,
  ERROR_CODES.EXPENSE_NOT_FOUND,
  ERROR_CODES.INVALID_MONEY_AMOUNT,
  ERROR_CODES.INVALID_CURRENCY,
  ERROR_CODES.INVALID_EXCHANGE_RATE,
  ERROR_CODES.EXCHANGE_RATE_NOT_FOUND,
  ERROR_CODES.REMINDER_NOT_FOUND,
  ERROR_CODES.REMINDER_OCCURRENCE_NOT_FOUND,
  ERROR_CODES.INVALID_TIMEZONE,
  ERROR_CODES.INVALID_RRULE,
  ERROR_CODES.INVALID_REMINDER_STATE,
  ERROR_CODES.INVALID_OCCURRENCE_STATE,
  ERROR_CODES.INVALID_DELAY_TIME,
  ERROR_CODES.NOTIFICATION_NOT_FOUND,
  ERROR_CODES.NOTIFICATION_DELIVERY_NOT_FOUND,
  ERROR_CODES.NOTIFICATION_SETTINGS_NOT_FOUND,
  ERROR_CODES.NOTIFICATION_DISABLED,
  ERROR_CODES.NO_USABLE_NOTIFICATION_CHANNEL,
  ERROR_CODES.INVALID_NOTIFICATION_CHANNEL,
  ERROR_CODES.NOTIFICATION_CHANNEL_NOT_FOUND,
  ERROR_CODES.NOTIFICATION_CHANNEL_ALREADY_EXISTS,
] as const;

export interface ApiErrorBody {
  success: false;
  error: {
    code: ErrorCode;
    message: string;
  };
}

/**
 * 统一错误响应体。
 * `message` 只能是固定文案，绝不能包含原始 Token、Authorization 头、Secret 或 SQL 内部细节。
 */
export function errorResponse(code: ErrorCode, message: string): ApiErrorBody {
  return { success: false, error: { code, message } };
}

export const errorResponseSchema = z
  .object({
    success: z.literal(false),
    error: z.object({
      code: z.enum(ERROR_CODE_VALUES),
      message: z.string(),
    }),
  })
  .openapi("ApiError");
